import { IsString, Length } from 'class-validator';

import type { CreateApiKeyPayload } from '@cms/contracts';

/**
 * Name only. The key material is generated by the server — accepting a
 * caller-supplied secret would mean accepting a caller-chosen one, and the
 * `appId` comes from the route, never from the body.
 */
export class CreateApiKeyDto implements CreateApiKeyPayload {
  @IsString()
  @Length(1, 255)
  name: string;
}
